create extension if not exists vector;

create type public.agent_status as enum ('ACTIVE', 'PAUSED', 'ARCHIVED');
create type public.task_state as enum ('DRAFT', 'READY', 'QUEUED', 'RUNNING', 'WAITING_DEPENDENCY', 'WAITING_APPROVAL', 'WAITING_PROVIDER_QUOTA', 'WAITING_BUDGET_APPROVAL', 'BLOCKED', 'IMPLEMENTED', 'FAILED_RETRYABLE', 'FAILED_FINAL', 'CANCELED', 'VERIFYING', 'REVIEW_PENDING', 'FIX_REQUIRED', 'DONE');

create table public.agents (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, avatar_asset_id uuid, role_key text not null, title text not null default '', personality_json jsonb not null default '{}',
  base_instructions text not null default '', memory_namespace text not null, autonomy_mode public.autonomy_mode, status public.agent_status not null default 'ACTIVE',
  created_at timestamptz not null default now(), archived_at timestamptz
);
create table public.agent_assignments (id uuid primary key default gen_random_uuid(), agent_id uuid not null references public.agents(id) on delete cascade, team_id uuid references public.teams(id), project_id uuid references public.projects(id), reports_to_agent_id uuid references public.agents(id), active boolean not null default true, unique (agent_id, team_id, project_id));
create table public.provider_connections (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, provider_type text not null,
  display_name text not null, encrypted_secret_blob jsonb, auth_mode text not null, status text not null default 'UNVERIFIED', capabilities_json jsonb not null default '{}', last_verified_at timestamptz, created_at timestamptz not null default now()
);
create table public.model_catalog (id uuid primary key default gen_random_uuid(), provider_connection_id uuid references public.provider_connections(id) on delete cascade, provider_type text not null, provider_model_id text not null, display_name text not null, capabilities_json jsonb not null default '{}', pricing_json jsonb, status text not null default 'ACTIVE', discovered_at timestamptz not null default now());
create table public.agent_bindings (id uuid primary key default gen_random_uuid(), agent_id uuid not null references public.agents(id) on delete cascade, provider_connection_id uuid not null references public.provider_connections(id), provider_model_id text not null, runtime_type text not null, reasoning_effort text not null default 'standard', config_json jsonb not null default '{}', active_from timestamptz not null default now(), active_to timestamptz);
create unique index one_active_agent_binding on public.agent_bindings(agent_id) where active_to is null;
create table public.provider_sessions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, agent_id uuid not null references public.agents(id), task_id uuid, binding_id uuid not null references public.agent_bindings(id), external_session_id text not null, provider_metadata jsonb not null default '{}', started_at timestamptz not null default now(), ended_at timestamptz);

create table public.workflows (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid not null references public.projects(id), goal text not null, status text not null default 'IDLE', created_by_user_id uuid references auth.users(id), created_by_agent_id uuid references public.agents(id), root_task_id uuid, created_at timestamptz not null default now(), completed_at timestamptz);
create table public.tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid not null references public.projects(id), workflow_id uuid references public.workflows(id), parent_task_id uuid references public.tasks(id), title text not null, description text not null default '', task_type text not null, state public.task_state not null default 'DRAFT', priority int not null default 0, assigned_agent_id uuid references public.agents(id), read_scope_json jsonb not null default '[]', write_scope_json jsonb not null default '[]', definition_of_done_json jsonb not null default '{}', verification_json jsonb not null default '{}', parallel_group_id text, base_commit_sha text, candidate_commit_sha text, approved_design_version_id uuid, retry_count int not null default 0, max_retries int not null default 2, created_at timestamptz not null default now(), started_at timestamptz, completed_at timestamptz);
alter table public.workflows add constraint workflows_root_task_fk foreign key (root_task_id) references public.tasks(id);
create table public.task_dependencies (task_id uuid not null references public.tasks(id) on delete cascade, depends_on_task_id uuid not null references public.tasks(id) on delete cascade, dependency_type text not null default 'BLOCKING', primary key (task_id, depends_on_task_id), check (task_id <> depends_on_task_id));
create table public.task_attempts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, task_id uuid not null references public.tasks(id) on delete cascade, agent_id uuid not null references public.agents(id), provider_session_id uuid references public.provider_sessions(id), attempt_number int not null, state text not null, started_at timestamptz not null default now(), ended_at timestamptz, handoff_json jsonb, failure_class text, failure_detail text);
create table public.agent_runs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, task_attempt_id uuid references public.task_attempts(id), meeting_id uuid, agent_id uuid not null references public.agents(id), provider_session_id uuid references public.provider_sessions(id), state text not null, correlation_id uuid not null, external_run_id text, resume_token_metadata jsonb not null default '{}', last_event_at timestamptz, next_retry_at timestamptz, retry_reason text, started_at timestamptz not null default now(), ended_at timestamptz);
create table public.run_events (id bigint generated always as identity primary key, organization_id uuid not null references public.organizations(id) on delete cascade, run_id uuid not null references public.agent_runs(id) on delete cascade, seq int not null, event_type text not null, payload_json jsonb not null default '{}', created_at timestamptz not null default now(), unique(run_id, seq));
create table public.domain_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, aggregate_type text not null, aggregate_id uuid not null, event_type text not null, payload_json jsonb not null default '{}', correlation_id uuid not null, created_at timestamptz not null default now());
create table public.outbox_events (id uuid primary key default gen_random_uuid(), event_type text not null, payload_json jsonb not null default '{}', available_at timestamptz not null default now(), processed_at timestamptz, attempts int not null default 0);
alter table public.outbox_events enable row level security;
create policy outbox_service_role_only on public.outbox_events for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

create or replace function public.claim_outbox_event(p_now timestamptz default now())
returns setof public.outbox_events
language plpgsql
security definer
set search_path = public
as $$
declare claimed public.outbox_events;
begin
  select * into claimed
  from public.outbox_events
  where processed_at is null and available_at <= p_now
  order by available_at, id
  for update skip locked
  limit 1;
  if claimed.id is null then return; end if;
  update public.outbox_events set attempts = attempts + 1 where id = claimed.id returning * into claimed;
  return next claimed;
end;
$$;
revoke execute on function public.claim_outbox_event(timestamptz) from public, authenticated, anon;
grant execute on function public.claim_outbox_event(timestamptz) to service_role;

create table public.reviews (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid not null references public.projects(id), task_id uuid references public.tasks(id), reviewer_agent_id uuid not null references public.agents(id), candidate_sha text not null, status text not null, summary text not null default '', created_at timestamptz not null default now(), completed_at timestamptz);
create table public.review_findings (id uuid primary key default gen_random_uuid(), review_id uuid not null references public.reviews(id) on delete cascade, severity text not null, category text not null, title text not null, description text not null, evidence text not null, file_path text, symbol text, recommendation text not null, blocking boolean not null, confidence numeric not null check (confidence between 0 and 1));
create table public.verification_runs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, task_id uuid not null references public.tasks(id) on delete cascade, kind text not null, command_or_check text not null, status text not null, artifact_id uuid, duration_ms bigint not null default 0, executed_at timestamptz not null default now());
create table public.design_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid not null references public.projects(id), task_id uuid references public.tasks(id), designer_agent_id uuid not null references public.agents(id), brief text not null, status text not null default 'OPEN', created_at timestamptz not null default now());
create table public.design_versions (id uuid primary key default gen_random_uuid(), design_request_id uuid not null references public.design_requests(id) on delete cascade, version_number int not null, status text not null, spec_json jsonb not null default '{}', rationale text not null default '', preview_artifact_ids jsonb not null default '[]', created_at timestamptz not null default now(), approved_by uuid references auth.users(id), approved_at timestamptz, unique(design_request_id, version_number));
create unique index one_current_design on public.design_versions(design_request_id) where status = 'APPROVED';

create table public.conversations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id), conversation_type text not null, primary_agent_id uuid references public.agents(id), title text not null default '', created_at timestamptz not null default now(), archived_at timestamptz);
create table public.messages (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, conversation_id uuid not null references public.conversations(id) on delete cascade, sender_type text not null, sender_user_id uuid references auth.users(id), sender_agent_id uuid references public.agents(id), content_json jsonb not null, provider_metadata jsonb, created_at timestamptz not null default now());
create index messages_search_idx on public.messages using gin (to_tsvector('simple', coalesce(content_json->>'text', '')));
create table public.memories (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id), agent_id uuid references public.agents(id), memory_type text not null, title text not null, content text not null, importance int not null default 50, pinned boolean not null default false, source_type text, source_id uuid, embedding vector(1536), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.decisions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid not null references public.projects(id), title text not null, decision text not null, rationale text not null, consequences text not null default '', status text not null default 'ACTIVE', source_meeting_id uuid, source_message_id uuid, created_at timestamptz not null default now(), superseded_by uuid references public.decisions(id));

create table public.meetings (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid not null references public.projects(id), title text not null, meeting_type text not null, agenda_json jsonb not null default '[]', status text not null default 'DRAFT', convener_agent_id uuid references public.agents(id), created_by_user_id uuid references auth.users(id), max_rounds int not null default 2, started_at timestamptz, ended_at timestamptz);
create table public.meeting_participants (meeting_id uuid not null references public.meetings(id) on delete cascade, agent_id uuid references public.agents(id), user_id uuid references auth.users(id), participant_type text not null, primary key(meeting_id, agent_id, user_id));
create table public.meeting_contributions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, meeting_id uuid not null references public.meetings(id) on delete cascade, participant_type text not null, agent_id uuid references public.agents(id), user_id uuid references auth.users(id), round int not null, content text not null, run_id uuid references public.agent_runs(id), created_at timestamptz not null default now());
create table public.meeting_minutes (meeting_id uuid primary key references public.meetings(id) on delete cascade, summary text not null, decisions_json jsonb not null default '[]', action_items_json jsonb not null default '[]', generated_by_agent_id uuid references public.agents(id), approved_at timestamptz);

create table public.approvals (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id), approval_type text not null, requested_by_agent_id uuid references public.agents(id), requested_by_user_id uuid references auth.users(id), subject_type text not null, subject_id uuid not null, status text not null default 'PENDING', risk_json jsonb not null default '{}', alternatives_json jsonb not null default '[]', expires_at timestamptz, resolved_by_user_id uuid references auth.users(id), resolution_note text, created_at timestamptz not null default now(), resolved_at timestamptz);
create table public.cost_ledger (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id), task_id uuid references public.tasks(id), run_id uuid references public.agent_runs(id), meeting_id uuid references public.meetings(id), agent_id uuid references public.agents(id), provider_type text not null, provider_model_id text not null, currency text not null default 'USD', amount numeric not null check(amount >= 0), input_tokens bigint, cached_input_tokens bigint, output_tokens bigint, confidence text not null, occurred_at timestamptz not null default now());
create table public.budget_policies (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id), agent_id uuid references public.agents(id), period_type text not null, soft_limit numeric not null default 0, hard_limit numeric not null default 0, currency text not null default 'USD', action_on_soft text not null, action_on_hard text not null, enabled boolean not null default true);
create table public.notifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, category text not null, severity text not null, title text not null, body text not null, deep_link text not null, read_at timestamptz, created_at timestamptz not null default now());
create table public.push_subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, endpoint text not null, p256dh text not null, auth text not null, user_agent text not null default '', created_at timestamptz not null default now(), revoked_at timestamptz);
create table public.worker_nodes (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id) on delete cascade, node_type text not null, name text not null, status text not null, credential_hash text not null, capabilities_json jsonb not null default '{}', allowed_scopes_json jsonb not null default '{}', last_heartbeat_at timestamptz, created_at timestamptz not null default now(), revoked_at timestamptz);
create table public.worker_leases (id uuid primary key default gen_random_uuid(), worker_node_id uuid not null references public.worker_nodes(id) on delete cascade, task_attempt_id uuid not null references public.task_attempts(id) on delete cascade, lease_expires_at timestamptz not null, renewed_at timestamptz not null default now());
create table public.repo_connections (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, provider_type text not null, repo_owner text not null, repo_name text not null, repo_external_id text not null, encrypted_auth_blob jsonb, default_branch text not null default 'main', status text not null default 'REQUIRES_AUTH', created_at timestamptz not null default now());
create table public.artifacts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id), task_id uuid references public.tasks(id), artifact_type text not null, storage_path text not null, mime_type text not null, sha256 text not null, size_bytes bigint not null, metadata_json jsonb not null default '{}', created_at timestamptz not null default now());

do $$
declare table_name text;
begin
  foreach table_name in array array['agents','provider_connections','provider_sessions','workflows','tasks','task_attempts','agent_runs','run_events','domain_events','reviews','verification_runs','design_requests','conversations','messages','memories','decisions','meetings','meeting_contributions','approvals','cost_ledger','budget_policies','notifications','worker_nodes','repo_connections','artifacts'] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('create policy %I on public.%I for all using (public.is_organization_member(organization_id)) with check (public.is_organization_member(organization_id))', table_name || '_tenant_isolation', table_name);
  end loop;
end $$;

alter table public.agent_assignments enable row level security;
create policy agent_assignment_tenant_isolation on public.agent_assignments for all using (exists (select 1 from public.agents a where a.id = agent_id and public.is_organization_member(a.organization_id)));
alter table public.agent_bindings enable row level security;
create policy agent_binding_tenant_isolation on public.agent_bindings for all using (exists (select 1 from public.agents a where a.id = agent_id and public.is_organization_member(a.organization_id)));
alter table public.model_catalog enable row level security;
create policy model_catalog_tenant_isolation on public.model_catalog for all using (provider_connection_id is null or exists (select 1 from public.provider_connections p where p.id = provider_connection_id and public.is_organization_member(p.organization_id)));
alter table public.meeting_participants enable row level security;
create policy meeting_participant_tenant_isolation on public.meeting_participants for all using (exists (select 1 from public.meetings m where m.id = meeting_id and public.is_organization_member(m.organization_id)));
alter table public.meeting_minutes enable row level security;
create policy meeting_minutes_tenant_isolation on public.meeting_minutes for all using (exists (select 1 from public.meetings m where m.id = meeting_id and public.is_organization_member(m.organization_id)));
alter table public.push_subscriptions enable row level security;
create policy push_subscription_self_access on public.push_subscriptions for all using (user_id = auth.uid()) with check (user_id = auth.uid());
